# "service" is the name of this project. This will also be added to your AWS resource names.
service: shop

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }

functions:
  createProduct:
    handler: handler.createProduct
    events:
      - httpApi:
          path: /products
          method: post
          authorizer: customAuthorizer
  readProduct:
    handler: handler.readProduct
    events:
      - httpApi:
          path: /product/{id}
          method: get
          authorizer: customAuthorizer
  updateProduct:
    handler: handler.updateProduct
    events:
      - httpApi:
          path: /product/{id}
          method: put
          authorizer: customAuthorizer
  deleteProduct:
    handler: handler.deleteProduct
    events:
      - httpApi:
          path: /product/{id}
          method: delete
          authorizer: customAuthorizer
  listProducts:
    handler: handler.listProducts
    events:
      - httpApi:
          path: /products
          method: get
          authorizer: customAuthorizer
  authorizerFunc:
    handler: handler.authorizerFunc

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

